version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    restart: always
    volumes:
      - ./volumes/jellyfin-config:/config
      - ./volumes/data:/data

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./volumes/jackett-config:/config

  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    network_mode: host
    restart: always
    environment:
      - RPC_SECRET=${ARIA2_SECRET}
      - RPC_PORT=6800
    volumes:
      - ./volumes/aria2-config:/config
      - ./volumes/data:/downloads

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./volumes/sonarr-config:/config
      - ./volumes/data:/data
      - ./volumes/data:/downloads
