services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    restart: always
    volumes:
      - ./volumes/jellyfin-config:/config
      - ./volumes/data:/data

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - ./volumes/jackett-config:/config
      - ./volumes/data/jackett:/downloads

  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    network_mode: host
    restart: always
    environment:
      - RPC_SECRET=***      - RPC_PORT=6800
      - TZ=Africa/Nairobi
    volumes:
      - ./volumes/aria2-config:/config
      - ./volumes/data/aria2:/downloads

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - ./volumes/sonarr-config:/config
      - ./volumes/data:/data
      - ./volumes/data/sonarr:/downloads

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - ./volumes/radarr-config:/config
      - ./volumes/data:/data
      - ./volumes/data/radarr:/downloads
